@ECHO ON
set MAKEFILE_PATH_SEARCH=".."
set MAKEFILE_CONFIG_NAME="MakefileConfig.txt"
set DEBUG="True"
set DIVIDING_LINE_CHAR="+"
set DIVIDING_LINE_LENGTH="200"
"python" "Makefile.py" MAKEFILE_PATH_SEARCH=%MAKEFILE_PATH_SEARCH% MAKEFILE_CONFIG_NAME=%MAKEFILE_CONFIG_NAME% DEBUG=%DEBUG% DIVIDING_LINE_CHAR=%DIVIDING_LINE_CHAR% DIVIDING_LINE_LENGTH=%DIVIDING_LINE_LENGTH%
set /p=Press Enter to Continue...